/**
 * Unit tests for `JwtAuthGuard`.
 *
 * Uses a real `Reflector` against a class carrying a real `@Public()`, so the
 * decorator and its metadata key are covered alongside the guard itself. The
 * token verifier is stubbed - its own behaviour is covered by
 * `keycloak-token.verifier.spec.ts`.
 *
 * Generated by Claude Code (Claude Opus 5).
 */
import { ExecutionContext, UnauthorizedException } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { JwtAuthGuard } from './jwt-auth.guard.ts';
import { Public } from '../../presentation/decorators/public.decorator.ts';
import { AuthenticatedUser } from '../../domain/authenticated-user.entity.ts';

class Routes {
  @Public() open() {}
  closed() {}
}

const USER = AuthenticatedUser.create('u1', 'a@b.c', ['user']);
const verifier = { verify: vi.fn() };
const guard = new JwtAuthGuard(verifier as never, new Reflector());

const ctx = (handler: () => void, headers: Record<string, string> = {}) => {
  const req: Record<string, unknown> = { headers };

  return {
    switchToHttp: () => ({ getRequest: () => req }),
    getHandler: () => handler,
    getClass: () => Routes,
    __req: req,
  } as unknown as ExecutionContext & { __req: Record<string, unknown> };
};

beforeEach(() => {
  verifier.verify.mockReset();
  verifier.verify.mockResolvedValue(USER);
});

it('lets @Public through without touching the verifier', async () => {
  await expect(guard.canActivate(ctx(Routes.prototype.open))).resolves.toBe(
    true,
  );
  expect(verifier.verify).not.toHaveBeenCalled();
});

it('attaches the verified user to the request', async () => {
  const context = ctx(Routes.prototype.closed, {
    authorization: 'Bearer good',
  });

  await expect(guard.canActivate(context)).resolves.toBe(true);
  expect(verifier.verify).toHaveBeenCalledWith('good');
  expect(context.__req.user).toBe(USER);
});

it('accepts a lowercase bearer scheme (RFC 7235)', async () => {
  await expect(
    guard.canActivate(
      ctx(Routes.prototype.closed, { authorization: 'bearer good' }),
    ),
  ).resolves.toBe(true);
});

it.each([
  ['no header', undefined],
  ['empty', ''],
  ['scheme only', 'Bearer'],
  ['double space', 'Bearer  tok'],
  ['wrong scheme', 'Basic abc'],
  ['bare token', 'good'],
])('rejects %s', async (_label, authorization) => {
  const headers: Record<string, string> = {};
  if (authorization !== undefined) headers.authorization = authorization;

  await expect(
    guard.canActivate(ctx(Routes.prototype.closed, headers)),
  ).rejects.toThrow(UnauthorizedException);
  expect(verifier.verify).not.toHaveBeenCalled();
});

it('propagates a verifier rejection', async () => {
  verifier.verify.mockRejectedValue(new UnauthorizedException());

  await expect(
    guard.canActivate(
      ctx(Routes.prototype.closed, { authorization: 'Bearer bad' }),
    ),
  ).rejects.toThrow(UnauthorizedException);
});
