/**
 * Unit tests for `RolesGuard`.
 *
 * Uses a real `Reflector` against classes carrying real `@Roles()` / `@Public()`
 * decorators, so decorator metadata resolution is covered alongside the guard.
 *
 * Note: the "allows a route with no @Roles" case pins current behaviour -
 * authentication is default-deny, authorization is opt-in. If `RolesGuard` ever
 * switches to default-deny, that test should flip to expect a throw.
 *
 * Generated by Claude Code (Claude Opus 5).
 */
import { ExecutionContext, ForbiddenException } from '@nestjs/common';
import { Reflector } from '@nestjs/core';
import { RolesGuard } from './roles.guard.ts';
import { Roles } from '../../presentation/decorators/roles.decorator.ts';
import { Public } from '../../presentation/decorators/public.decorator.ts';
import { AuthenticatedUser } from '../../domain/authenticated-user.entity.ts';
import { UserRole } from '../../domain/user-role.ts';

class Routes {
  @Public() open() {}
  unrestricted() {}
  @Roles(UserRole.Admin) adminOnly() {}
  @Roles(UserRole.Admin, UserRole.User) either() {}
}

@Roles(UserRole.Admin)
class AdminRoutes {
  inherited() {}
}

const guard = new RolesGuard(new Reflector());
const admin = AuthenticatedUser.create('u1', null, [UserRole.Admin]);
const plain = AuthenticatedUser.create('u2', null, [UserRole.User]);
const noRoles = AuthenticatedUser.create('u3', null, []);

const ctx = (
  handler: () => void,
  user?: AuthenticatedUser,
  cls: object = Routes,
) =>
  ({
    switchToHttp: () => ({ getRequest: () => ({ user }) }),
    getHandler: () => handler,
    getClass: () => cls,
  }) as unknown as ExecutionContext;

it('lets @Public through even with no user', () => {
  expect(guard.canActivate(ctx(Routes.prototype.open))).toBe(true);
});

it('allows a route with no @Roles (authorization is opt-in)', () => {
  expect(guard.canActivate(ctx(Routes.prototype.unrestricted, noRoles))).toBe(
    true,
  );
});

it('allows a user holding the required role', () => {
  expect(guard.canActivate(ctx(Routes.prototype.adminOnly, admin))).toBe(true);
});

it('allows if the user holds any one of several required roles', () => {
  expect(guard.canActivate(ctx(Routes.prototype.either, plain))).toBe(true);
});

it('forbids a user missing the required role', () => {
  expect(() =>
    guard.canActivate(ctx(Routes.prototype.adminOnly, plain)),
  ).toThrow(ForbiddenException);
});

it('forbids when no user is attached (guard-order safeguard)', () => {
  expect(() =>
    guard.canActivate(ctx(Routes.prototype.adminOnly, undefined)),
  ).toThrow(ForbiddenException);
});

it('inherits class-level @Roles onto every handler', () => {
  expect(
    guard.canActivate(ctx(AdminRoutes.prototype.inherited, admin, AdminRoutes)),
  ).toBe(true);
  expect(() =>
    guard.canActivate(ctx(AdminRoutes.prototype.inherited, plain, AdminRoutes)),
  ).toThrow(ForbiddenException);
});
