apiVersion: batch/v1
kind: Job
metadata:
  name: planee-db-migrate
  namespace: planee
  labels:
    app: planee-db-migrate
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: planee-db-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: registry.cloud.martinpetr.dev/planee/db-migration:sha-e06d268
          envFrom:
            - configMapRef:
                name: planee-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: planee-postgres-cluster-app # CNPG generated
                  key: uri
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
