apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: planee
resources:
  - namespace.yaml
  - postgres.yaml
  - api.yaml
  - config.yaml
  - db-migration.yaml
  - sa.yaml
  - web.yaml
  - marketing-web.yaml
  - flipt.yaml
