apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: planee-postgres-cluster
  namespace: planee
spec:
  instances: 3

  bootstrap:
    initdb:
      database: app
      owner: app

  storage:
    size: 2Gi
