/**
 * Unit tests for `PrismaUserRepository`.
 *
 * The Prisma client is stubbed: these assert the *query shape*, which is where
 * the design decision lives - a single idempotent upsert that never writes over
 * an existing row. Whether Postgres really collapses concurrent inserts is the
 * database's contract, not this class's; that needs an integration test.
 *
 * Generated by Claude Code (Claude Opus 5).
 */
import { PrismaUserRepository } from './prisma-user.repository.ts';

const db = { user: { upsert: vi.fn() } };
const repository = new PrismaUserRepository(db as never);

beforeEach(() => {
  db.user.upsert.mockReset();
  db.user.upsert.mockResolvedValue({ id: 'sub-1' });
});

it('upserts the subject as the primary key', async () => {
  await repository.ensureProvisioned('sub-1');

  expect(db.user.upsert).toHaveBeenCalledWith({
    where: { id: 'sub-1' },
    create: { id: 'sub-1' },
    update: {},
  });
});

it('leaves an existing row untouched', async () => {
  await repository.ensureProvisioned('sub-1');

  // An empty `update` is what makes a second call a no-op instead of a write.
  expect(db.user.upsert.mock.calls[0][0].update).toEqual({});
});

it('never reads before writing', async () => {
  await repository.ensureProvisioned('sub-1');

  // find-then-create would race on first login; the mobile app fires several
  // requests at once as soon as it has a token.
  expect(Object.keys(db.user)).toEqual(['upsert']);
  expect(db.user.upsert).toHaveBeenCalledTimes(1);
});

it('propagates a database failure', async () => {
  db.user.upsert.mockRejectedValue(new Error('db down'));

  await expect(repository.ensureProvisioned('sub-1')).rejects.toThrow('db down');
});
