/**
 * Unit tests for `KeycloakTokenVerifier`.
 *
 * Signs real RS256 tokens against a throwaway keypair and serves the matching
 * JWKS from a local HTTP server, so the actual `jose` verification path runs
 * unmocked.
 *
 * Generated by Claude Code (Claude Opus 5).
 */
import { createServer, Server } from 'http';
import { KeycloakTokenVerifier } from './keycloak-token.verifier.ts';
import { exportJWK, generateKeyPair, SignJWT } from 'jose';
import { UnauthorizedException } from '@nestjs/common';

const AUDIENCE = 'api';
let server: Server;
let issuer: string;
let privateKey: CryptoKey;
let publicKey: CryptoKey;
let verifier: KeycloakTokenVerifier;

beforeAll(async () => {
  ({ publicKey, privateKey } = await generateKeyPair('RS256', {
    extractable: true,
  }));

  const jwk = {
    ...(await exportJWK(publicKey)),
    kid: 'test-key',
    alg: 'RS256',
    use: 'sig',
  };

  server = createServer((_, res) => {
    res.setHeader('Content-Type', 'application/json');
    res.end(JSON.stringify({ keys: [jwk] }));
  });

  await new Promise<void>((r) => server.listen(0, '127.0.0.1', () => r()));

  issuer = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
  verifier = new KeycloakTokenVerifier(issuer, AUDIENCE);
});

afterAll(() => void server.close());

const mint = (
  claims: Record<string, unknown> = {},
  {
    alg = 'RS256',
    key = privateKey,
    iss = issuer,
    aud = AUDIENCE,
    expires = '5m',
  } = {},
) =>
  new SignJWT({
    typ: 'Bearer',
    sub: 'user-1',
    ...claims,
  })
    .setProtectedHeader({ alg, kid: 'test-key' })
    .setIssuer(iss)
    .setAudience(aud)
    .setIssuedAt()
    .setExpirationTime(expires)
    .sign(key);

const expectRejected = (token: Promise<string> | string) =>
  expect(
    Promise.resolve(token).then((t) => verifier.verify(t)),
  ).rejects.toThrow(UnauthorizedException);

describe('accepts', () => {
  it('a valid Keycloak access token', async () => {
    const user = await verifier.verify(
      await mint({ email: 'a@b.c', realm_access: { roles: ['admin'] } }),
    );
    expect(user.hasRole('admin')).toBe(true);
  });

  it('a token with no email', async () => {
    await expect(
      verifier.verify(await mint({ realm_access: { roles: ['admin'] } })),
    ).resolves.toBeDefined();
  });

  it('an aud array that merely contains the audience', async () => {
    await expect(
      verifier.verify(await mint({}, { aud: [AUDIENCE, 'account'] as never })),
    ).resolves.toBeDefined();
  });
});

describe('role mapping', () => {
  it('drops realm roles the app does not define', async () => {
    const user = await verifier.verify(
      await mint({
        realm_access: {
          roles: ['admin', 'offline_access', 'uma_authorization'],
        },
      }),
    );

    expect(user.hasRole('admin')).toBe(true);
    expect(user.hasRole('user')).toBe(false);
  });

  it('yields no roles when realm_access is absent', async () => {
    const user = await verifier.verify(await mint());

    expect(user.hasRole('admin')).toBe(false);
    expect(user.hasRole('user')).toBe(false);
  });
});

describe('rejects', () => {
  it('an ID token (typ confusion)', () => expectRejected(mint({ typ: 'ID' })));
  it('a refresh token', () => expectRejected(mint({ typ: 'Refresh' })));
  it('an offline token', () => expectRejected(mint({ typ: 'Offline' })));
  it('a token with no typ at all', () =>
    expectRejected(mint({ typ: undefined })));

  it('a token for a different audience', () =>
    expectRejected(mint({}, { aud: 'other-api' })));
  it('a token from a different issuer', () =>
    expectRejected(mint({}, { iss: 'https://evil.example' })));
  it('an expired token', () => expectRejected(mint({}, { expires: '-1h' })));
  it('a token with no sub', () => expectRejected(mint({ sub: undefined })));

  it('an alg=none token', () => {
    const b64 = (o: unknown) =>
      Buffer.from(JSON.stringify(o)).toString('base64url');

    return expectRejected(
      `${b64({ alg: 'none', kid: 'test-key' })}.${b64({
        typ: 'Bearer',
        sub: 'attacker',
        iss: issuer,
        aud: AUDIENCE,
        exp: Math.floor(Date.now() / 1000) + 300,
      })}.`,
    );
  });

  it('an HS256 token signed with the RSA public key (alg confusion)', async () => {
    const spki = await crypto.subtle.exportKey('spki', publicKey);
    const hmac = await crypto.subtle.importKey(
      'raw',
      spki,
      { name: 'HMAC', hash: 'SHA-256' },
      false,
      ['sign'],
    );

    await expectRejected(
      mint({ sub: 'attacker' }, { alg: 'HS256', key: hmac }),
    );
  });

  it('a token signed by a key outside the realm JWKS', async () => {
    const foreign = await generateKeyPair('RS256', { extractable: true });

    await expectRejected(
      mint({ sub: 'attacker' }, { key: foreign.privateKey }),
    );
  });

  it('a structurally invalid token', () => expectRejected('not-a-jwt'));
});
